In [1]:
import torch

In [2]:
torch.__version__

'2.7.1+cpu'

In [3]:
x = torch.empty(4,2)

In [4]:
print(x)

tensor([[1.6950e-21, 1.0061e-42],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])


In [5]:
x.size()

torch.Size([4, 2])

In [6]:
x = torch.randn(4,2)

In [7]:
print(x)

tensor([[-0.8359, -0.1036],
        [ 1.5402, -1.8467],
        [ 1.5919, -1.2230],
        [ 0.4469, -1.7429]])


In [8]:
x = torch.zeros(4,2, dtype=torch.long)

In [9]:
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [10]:
x = torch.tensor([3,2])

In [11]:
print(x)

tensor([3, 2])


In [12]:
x = x.new_ones(2,4,dtype=torch.double)

In [13]:
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [18]:
x = torch.randn_like(x, dtype=torch.float)

In [19]:
print(x)

tensor([[ 1.4892, -0.0675, -0.5226,  0.2071],
        [ 1.3072,  0.3355, -0.4793, -2.4486]])


In [22]:
ft = torch.FloatTensor([1,2,3])

In [23]:
print(ft.dtype)

torch.float32


In [24]:
print(ft.short())

tensor([1, 2, 3], dtype=torch.int16)


In [27]:
print(ft.int())

tensor([1, 2, 3], dtype=torch.int32)


In [29]:
it = torch.IntTensor([1,2,3])

In [30]:
print(it)

tensor([1, 2, 3], dtype=torch.int32)


In [32]:
print(it.double())

tensor([1., 2., 3.], dtype=torch.float64)


In [33]:
print(it.float())

tensor([1., 2., 3.])


In [34]:
print(it.half())

tensor([1., 2., 3.], dtype=torch.float16)


In [35]:
x = torch.randn(1)

In [36]:
print(x)

tensor([-0.0557])


In [37]:
print(x.dtype)

torch.float32


In [39]:
print(x.item())

-0.05566421151161194


In [41]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [43]:
print(device)

cpu


In [45]:
y = torch.ones_like(x, device=device)

In [46]:
x = x.to(device)

In [47]:
z = x + y

In [49]:
print(z.device)

cpu


In [50]:
print(z)

tensor([0.9443])


In [56]:
x = torch.randn(1)

In [54]:
print(x)

tensor([0.6573])


In [57]:
t0 = torch.tensor(0)

In [60]:
print(t0.size())

torch.Size([])


In [61]:
print(t0.shape)

torch.Size([])


In [82]:
t1 = torch.tensor([[[1,2,3],[2,3,4]], [[1,2,3],[2,3,4]]])

In [88]:
print(t1[0].size())

torch.Size([2, 3])


In [89]:
print(t1.shape)

torch.Size([2, 2, 3])


In [90]:
print(t1)

tensor([[[1, 2, 3],
         [2, 3, 4]],

        [[1, 2, 3],
         [2, 3, 4]]])


In [91]:
print(t1.ndim)

3


In [92]:
import math

In [93]:
a = torch.rand(1,2)*2 -1

In [94]:
print(a)

tensor([[-0.5916, -0.3263]])


In [95]:
print(torch.abs(a))

tensor([[0.5916, 0.3263]])


In [96]:
print(torch.ceil(a))

tensor([[-0., -0.]])


In [97]:
print(torch.floor(a))

tensor([[-1., -1.]])


In [98]:
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.5000, -0.3263]])


In [99]:
print(a)

tensor([[-0.5916, -0.3263]])


In [100]:
print(torch.max(a))

tensor(-0.3263)


In [101]:
print(torch.min(a))

tensor(-0.5916)


In [102]:
print(torch.mean(a))

tensor(-0.4590)


In [103]:
print(torch.std(a))

tensor(0.1876)


In [137]:
print(a)
print(torch.prod(a))

tensor([[-0.0042,  0.0890],
        [ 0.6020,  0.7317]])
tensor(-0.0002)


In [135]:
print(torch.unique(a))

tensor([-0.0042,  0.0890,  0.6020,  0.7317])


In [109]:
print(torch.argmin(a))

tensor(0)


In [110]:
print(torch.argmax(a))

tensor(1)


In [111]:
a = torch.randn(2,2)

In [112]:
print(a.max())

tensor(0.7317)


In [113]:
print(a.max(dim=0))

torch.return_types.max(
values=tensor([0.6020, 0.7317]),
indices=tensor([1, 1]))


In [114]:
print(a)

tensor([[-0.0042,  0.0890],
        [ 0.6020,  0.7317]])


In [115]:
print(a.max(dim=1))

torch.return_types.max(
values=tensor([0.0890, 0.7317]),
indices=tensor([1, 1]))


In [116]:
b = torch.randn(2,2)

In [117]:
print(a+b)

tensor([[ 0.6110,  0.2452],
        [-0.0158,  1.7481]])


In [126]:
result = torch.randn(2,4)

In [127]:
print(result)
print(torch.add(a,b,out=result))

tensor([[ 1.6981,  0.1865, -0.1203, -0.1301],
        [ 0.1551, -1.8393,  0.5424, -0.3033]])
tensor([[ 0.6110,  0.2452],
        [-0.0158,  1.7481]])


C:\Users\user\AppData\Local\Temp\ipykernel_27824\3719085794.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\Resize.cpp:37.)
  print(torch.add(a,b,out=result))


In [128]:
print(a.add_(b))

tensor([[ 0.6110,  0.2452],
        [-0.0158,  1.7481]])


In [129]:
print(a.sub_(b))

tensor([[-0.0042,  0.0890],
        [ 0.6020,  0.7317]])


In [130]:
print(a//b)

tensor([[-1.,  0.],
        [-1.,  0.]])


In [131]:
print(a%b)

tensor([[ 0.6110,  0.0890],
        [-0.0158,  0.7317]])


In [132]:
print(b)

tensor([[ 0.6152,  0.1562],
        [-0.6178,  1.0164]])


In [133]:
print(a)

tensor([[-0.0042,  0.0890],
        [ 0.6020,  0.7317]])


In [138]:
torch.matmul(a,b)

tensor([[-0.0576,  0.0898],
        [-0.0817,  0.8377]])

In [140]:
torch.mm(a,b)

tensor([[-0.0576,  0.0898],
        [-0.0817,  0.8377]])

In [141]:
z = torch.mm(a,b)

In [142]:
torch.svd(z)

torch.return_types.svd(
U=tensor([[ 0.1124,  0.9937],
        [ 0.9937, -0.1124]]),
S=tensor([0.8471, 0.0483]),
V=tensor([[-0.1035, -0.9946],
        [ 0.9946, -0.1035]]))

In [143]:
x = torch.Tensor([[1,2],[3,4]])

In [146]:
print(x[0,0])

tensor(1.)


In [147]:
print(x[:,0])

tensor([1., 3.])


In [148]:
print(x[:,1])

tensor([2., 4.])


In [152]:
y= torch.ones_like(x)

In [154]:
x = torch.randn(4,5)

In [157]:
print(x.view(20))

tensor([-0.1769, -0.8508, -1.0565,  0.6671, -0.4126, -0.1095, -0.4740,  1.0047,
         1.6568,  0.7322,  0.3058,  0.0858, -0.7071, -0.4054,  0.0947,  0.3159,
         0.9011,  0.3546,  0.8699,  1.0805])


In [158]:
print(x.view(5,-1))

tensor([[-0.1769, -0.8508, -1.0565,  0.6671],
        [-0.4126, -0.1095, -0.4740,  1.0047],
        [ 1.6568,  0.7322,  0.3058,  0.0858],
        [-0.7071, -0.4054,  0.0947,  0.3159],
        [ 0.9011,  0.3546,  0.8699,  1.0805]])


In [162]:
print(x[0][0].item())

-0.1769344061613083


In [163]:
print(x.squeeze())

tensor([[-0.1769, -0.8508, -1.0565,  0.6671, -0.4126],
        [-0.1095, -0.4740,  1.0047,  1.6568,  0.7322],
        [ 0.3058,  0.0858, -0.7071, -0.4054,  0.0947],
        [ 0.3159,  0.9011,  0.3546,  0.8699,  1.0805]])


In [170]:
a = torch.rand(2,3,3)
print(a)

tensor([[[0.1668, 0.0044, 0.6729],
         [0.4319, 0.8700, 0.4964],
         [0.5652, 0.5734, 0.7541]],

        [[0.1395, 0.1595, 0.4768],
         [0.1009, 0.1123, 0.5030],
         [0.5107, 0.2616, 0.8898]]])


In [171]:
print(a.shape)

torch.Size([2, 3, 3])


In [172]:
print(a.squeeze())

tensor([[[0.1668, 0.0044, 0.6729],
         [0.4319, 0.8700, 0.4964],
         [0.5652, 0.5734, 0.7541]],

        [[0.1395, 0.1595, 0.4768],
         [0.1009, 0.1123, 0.5030],
         [0.5107, 0.2616, 0.8898]]])


In [178]:
print(a.unsqueeze(dim=1).shape)

torch.Size([2, 1, 3, 3])


In [175]:
print(a)

tensor([[[0.1668, 0.0044, 0.6729],
         [0.4319, 0.8700, 0.4964],
         [0.5652, 0.5734, 0.7541]],

        [[0.1395, 0.1595, 0.4768],
         [0.1009, 0.1123, 0.5030],
         [0.5107, 0.2616, 0.8898]]])


In [176]:
print(a.squeeze())

tensor([[[0.1668, 0.0044, 0.6729],
         [0.4319, 0.8700, 0.4964],
         [0.5652, 0.5734, 0.7541]],

        [[0.1395, 0.1595, 0.4768],
         [0.1009, 0.1123, 0.5030],
         [0.5107, 0.2616, 0.8898]]])


In [179]:
x = torch.FloatTensor([1,4])

In [180]:
print(x)

tensor([1., 4.])


In [208]:
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
res = torch.stack((z,y,z))

In [209]:
print(res)

tensor([[3., 6.],
        [2., 5.],
        [3., 6.]])


In [189]:
res = torch.concat((x,y),dim=0)

In [187]:
print(res)

tensor([1., 4., 2., 5.])


In [190]:
a = torch.randn(1,3,3)

In [191]:
b = torch.randn(1,3,3)

In [207]:
c = torch.concat((a,b), dim=2)

In [206]:
print(c)
print(c.shape)

tensor([[[-0.4191, -0.2859, -1.2150],
         [ 0.4584, -0.8559, -0.6551],
         [ 0.2341, -1.7936,  0.5898]],

        [[-0.3361,  0.7583, -0.0948],
         [ 1.6717, -0.3747, -1.2015],
         [-0.0031, -0.4484, -1.8595]]])
torch.Size([2, 3, 3])


In [212]:
t = torch.randn(3, 6)
print(t)

tensor([[-0.2946, -0.8458,  0.4697, -1.3641,  1.6468,  0.0424],
        [ 0.7566, -0.4984, -0.0808,  0.6200,  0.7419, -0.1117],
        [-0.1920, -0.7354, -1.3570,  1.3228, -0.9309,  0.6681]])


In [217]:
t1, t2, t3 = torch.chunk(t, 3, dim=1)

In [218]:
print(t1)

tensor([[-0.2946, -0.8458],
        [ 0.7566, -0.4984],
        [-0.1920, -0.7354]])


In [232]:
t4 = torch.split(t, 1, dim=0)

In [233]:
print(t4)

(tensor([[-0.2946, -0.8458,  0.4697, -1.3641,  1.6468,  0.0424]]), tensor([[ 0.7566, -0.4984, -0.0808,  0.6200,  0.7419, -0.1117]]), tensor([[-0.1920, -0.7354, -1.3570,  1.3228, -0.9309,  0.6681]]))


In [235]:
a = torch.randn(6)
print(a)

tensor([ 0.5483, -0.7529,  2.1831,  0.3814, -1.4315,  1.3372])


In [237]:
print(torch.chunk(a, 2, dim=0))

(tensor([ 0.5483, -0.7529,  2.1831]), tensor([ 0.3814, -1.4315,  1.3372]))


In [238]:
print(torch.split(a, 2, dim=0))

(tensor([ 0.5483, -0.7529]), tensor([2.1831, 0.3814]), tensor([-1.4315,  1.3372]))


In [239]:
a = torch.ones(7)

In [240]:
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [241]:
b = a.numpy()

In [242]:
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [243]:
a.add_(1)

tensor([2., 2., 2., 2., 2., 2., 2.])

In [244]:
print(b)

[2. 2. 2. 2. 2. 2. 2.]


In [247]:
import numpy as np

In [249]:
a = np.ones(7)

In [250]:
b = torch.from_numpy(a)

In [251]:
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64)


In [257]:
np.add(a,1)

array([3., 3., 3., 3., 3., 3., 3.])

In [258]:
print(a)

[2. 2. 2. 2. 2. 2. 2.]


In [259]:
a = torch.randn(3,3)

In [261]:
a = a * 3
print(a.requires_grad)

False


In [263]:
a.requires_grad_(True)

tensor([[  3.6589, -13.6681, -10.2178],
        [  0.0341,  -4.9244,   2.5087],
        [ -2.4814,  -3.4401,  -0.0648]], requires_grad=True)

In [264]:
b = (a*a).sum()

In [265]:
print(b)

tensor(353.1491, grad_fn=<SumBackward0>)


In [267]:
print(b.grad_fn)

In [269]:
x = torch.ones(3,3, requires_grad=True)

In [270]:
y = x+5

In [271]:
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [272]:
z = y*y

In [273]:
print(z)

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>)


In [274]:
out = z.mean()

In [275]:
print(out)

tensor(36., grad_fn=<MeanBackward0>)


In [276]:
out.backward()

In [277]:
print(x.grad)

tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


In [278]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [290]:
x=torch.randn(3, requires_grad=True)

In [291]:
y=x*2

In [292]:
while y.data.norm() < 1000:
    y = y*2

In [293]:
print(y)

tensor([ 792.0143,  811.7343, -363.0794], grad_fn=<MulBackward0>)


In [295]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

In [296]:
y.backward(v)

In [297]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [298]:
print(x.requires_grad)

True


In [299]:
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
False


In [304]:
print(x.requires_grad)

True


In [305]:
y=x.detach()

In [306]:
print(y.requires_grad)

False


In [307]:
print(x.eq(y).all())

tensor(True)


In [308]:
print(x)

tensor([ 0.7735,  0.7927, -0.3546], requires_grad=True)


In [309]:
print(y)

tensor([ 0.7735,  0.7927, -0.3546])


In [311]:
a = torch.ones(2,2,requires_grad=True)

In [314]:
print(a.grad)

None


In [315]:
print(a.grad_fn)

None


In [316]:
b = a + 2

In [317]:
print(a.grad)

None


In [318]:
print(a.grad_fn)

None


In [319]:
c = b**2

In [320]:
print(b.grad)

None


C:\Users\user\AppData\Local\Temp\ipykernel_27824\1999570874.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(b.grad)


In [321]:
out = c.sum()

In [322]:
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [324]:
out.backward()

In [325]:
print(a.data)

tensor([[1., 1.],
        [1., 1.]])


In [326]:
print(a.grad_fn)

None


In [328]:
print(a.grad)

tensor([[6., 6.],
        [6., 6.]])


In [330]:
print(c.data)
print(c.grad)
print(c.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


C:\Users\user\AppData\Local\Temp\ipykernel_27824\3875808255.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(c.grad)


In [331]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None


C:\Users\user\AppData\Local\Temp\ipykernel_27824\578081240.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print(out.grad)


In [ ]:
torch.permute()
torch.flatten()
torch.reshape()
torch.view()
torch.contiguous().view()
torch.squeeze()
torch.unsqueeze()
torch.transpose()
torch.expand()
torch.repeat()
torch.split()
torch.chunk()
torch.cat()
torch.stack()

torch.narrow()
torch.gather()
torch.unbind()



NameError: name 'torch' is not defined

In [ ]:
torch.reshape(input, shape)
torch.view(shape)
torch.contiguous().view()
torch.unsqueeze(input, dim)      #(3, 224, 224) to a batch of one (1, 3, 224, 224)  
torch.squeeze(input, dim=None)   #(Batch, 1) when you just want (Batch).
torch.permute(*dims)    
torch.transpose(input, dim0, dim1)
torch.flatten(input, start_dim=0, end_dim=-1)
torch.expand(*sizes)
torch.repeat(*sizes)
torch.chunk(input, chunks, dim=0)
torch.split(tensor, split_size_or_sections, dim=0)
torch.cat(tensors, dim=0)
torch.stack(tensors, dim=0)

torch.narrow(input, dim, start, length)
torch.gather(input, dim, index)
torch.unbind(input, dim=0)